name: Post report

on:
  schedule:
    - cron: '1 0 * * *'  # This triggers the workflow every day at 00:01 UTC

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets slack_sdk matplotlib

      - name: Run Script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          python post_report.py
