name: Run Script Every Minute

on:
  schedule:
    - cron: '*/5 * * * *'  # This triggers the workflow every 5 minutes

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets google-cloud-bigquery db-dtypes
          
      - name: Set up Google Credentials
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "google_credentials.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run Script
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json
        run: |
          python stargazers.py
          python pypi_downloads.py
